### ISSUE TITLE
PsychoStats changes default theme language

### ISSUE THREAD

**Issue by huobage** [Drek282/PsychoStats#109]
The default is en-US, and every time you access it, you need to adjust the default. How to make the homepage automatically default to other languages.

**Comment by Drek282** [comment]
I will look at that.  Thank you for the report.

**Comment by Drek282** [comment]
Ok, a few things.  First off, en_US is the only language at this time that is fully supported.  There is some minimal Serbian support.  When I choose Serbian, it does *stick*.  But in order for it to *stick*, you need to have accepted cookies.

So if you have done the work to add another language, first off, please submit that, because we desperately need more language support.  If it isn't *sticking* then something hasn't been coded properly when the language support was added.  Again, please submit what you have done, and I will look at it and fix it, if I can, if it is broken.

Finally, the default is en_US, and there is no way. at this time,  to configure another language as default.  I will put that on the "todo" list, and make it a priority.

**Comment by Drek282** [comment]
The other possibility, if the language choice isn't *sticking* is that there is a problem with cookie configuration in your webserver/host.

**Comment by Drek282** [comment]
A common cause of problems with cookies is https not functioning properly.

**Comment by Drek282** [comment]
One quick way to check if you are having problems with cookies is to install and enable more than one theme, then accept cookies and choose a different theme.  If that theme choice doesn't stick, you know you have a problem with either cookie configuration or https, because I know the theme choice works well when everything else is working properly.

**Comment by Rosenstein** [comment]
![image](https://github.com/user-attachments/assets/4e0d2d1a-ea65-46a7-a179-359b0f39f51a)
Here is the option where you set other languages as default ( if you have them ).

**Comment by Drek282** [comment]
There you go, I did not know that existed...

**Comment by huobage** [comment]
I have found the default language setting. I modified several commonly used local language files separately to prove that the default language can be set. The workload of translating the entire site is too huge to complete. Thank you for your answer.

In addition, I found that the Players list will become unresponsive after choosing to agree to the cookie. I use apache2.4 to deploy the site.

**Comment by Drek282** [comment]
Please provide a link to your site so I can check that behaviour.  That's not a behaviour I have ever seen, or that has ever been reported by anyone else.  That doesn't mean it isn't legit, but I will need to see it for myself to try to understand what could be causing it.

Also if you could provide what OS your server is running on, as well as what version of MySQL.

**Comment by huobage** [comment]
> Please provide a link to your site so I can check that behaviour. That's not a behaviour I have ever seen, or that has ever been reported by anyone else. That doesn't mean it isn't legit, but I will need to see it for myself to try to understand what could be causing it.
> 
> Also if you could provide what OS your server is running on, as well as what version of MySQL.

Currently the site and all game data have been cleared. I will wait for a few days for the game logs. I will contact you when the problem recurs.
My operating system is Centos7.9, database: MySQL 10.5.6-MariaDB

**Comment by Drek282** [comment]
Something is seriously screwed up with your installation.  Please reinstall from scratch, with no modified files.  That is not what the cookie consent popup should look like.

**Comment by Drek282** [comment]
Is that what Edge is showing on your computer, but Edge displays fine on other computers?

**Comment by Drek282** [comment]
I just ran a quick test with Edge on the demos and there were no issues.  I will need that link to have any idea of what is going on.  I may need you also to provide me with an admin account login so I can copy your settings.  You can email me at olstairs at rogers dot com with that if you are willing to do that.

**Comment by huobage** [comment]
> I just ran a quick test with Edge on the demos and there were no issues. I will need that link to have any idea of what is going on. I may need you also to provide me with an admin account login so I can copy your settings. You can email me at olstairs at rogers dot com with that if you are willing to do that.

Which of the above will be better for nginx and apache sites?

I used nginx before, and it would not open the page after agreeing to cookies. Now I have switched to apache and there are many problems. I don’t know if it is a problem with my deployment environment.

**Comment by Drek282** [comment]
**cheers**  I'm glad.  I will close this.
