### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by Rosenstein** [Drek282/PsychoStats#22]
Tracking issue.

- [x] Cookie consent
- [ ] 2.
- [ ] 3.

**Comment by Rosenstein** [comment]
How far we have come?
Cookie thingamajig was implemented.
How about User data download and user data deletion?

**Comment by Drek282** [comment]
User data download is kinda irrelevant because there is no user data kept other than what is displayed in the profiles.  There is no user tracking data to download.  Users and their game data can be deleted by an admin, but if they continue to play on the server they will show up in the stats again, or if the data is deleted and the logs are parsed again.

I don't really think the data download and data deletion are all that relevant.

**Comment by Drek282** [comment]
I think this can be closed.
